import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Home, BookOpen } from "lucide-react"; // 아이콘 추가

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "줏대 있게 살아",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 네비게이션 바 */}
        <nav className="bg-white shadow-sm border-b">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center py-4">
              <div className="flex items-center space-x-4">
                <Link href="/" className="text-2xl font-bold text-blue-600">
                  줏대 있게 살아
                </Link>
              </div>
              <div className="flex items-center space-x-4">
                {/* TODO: 로그인 여부에 따라 분기 */}
                <Link href="/login" className="text-gray-700 hover:text-blue-600">
                  로그인
                </Link>
                <Link
                  href="/register"
                  className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700"
                >
                  회원가입
                </Link>
              </div>
            </div>
          </div>
        </nav>

        {/* 전체 레이아웃 */}
        <div className="flex">
          {/* 사이드바 */}
          <aside className="w-64 bg-gradient-to-b from-gray-50 to-gray-100 h-screen p-6 border-r sticky top-0">
            <nav className="space-y-2">
              <Link
                href="/"
                className="flex items-center space-x-3 px-3 py-2 rounded-lg text-gray-700 hover:bg-blue-100 hover:text-blue-700 transition"
              >
                <Home size={18} />
                <span>요약하기</span>
              </Link>
              <Link
                href="/levelup"
                className="flex items-center space-x-3 px-3 py-2 rounded-lg text-gray-700 hover:bg-blue-100 hover:text-blue-700 transition"
              >
                <BookOpen size={18} />
                <span>레벨업 모드</span>
              </Link>
            </nav>
          </aside>

          {/* 본문 영역 */}
          <main className="flex-1 p-10 bg-gray-50 min-h-screen">{children}</main>
        </div>
      </body>
    </html>
  );
}
